export const config = {
    RPC_URL: 'https://rpc.devnet.publicawesome.dev',
    REST_URL: 'https://rest.devnet.publicawesome.dev',
    EXPLORER_URL: 'https://www.mintscan.io/stargaze',
    NETWORK_NAME: 'Stargaze-DEVNET',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'stargaze-devnet-1',
    CHAIN_NAME: 'Stargaze-DEVNET',
    COIN_DENOM: 'STARS',
    COIN_MINIMAL_DENOM: 'ustars',
    COIN_DECIMALS: 6,
    PREFIX: 'stars',
    COIN_TYPE: 118,
    COINGECKO_ID: 'stargaze',
    DEFAULT_GAS: 250000,
    GAS_PRICE_STEP_LOW: 0.005,
    GAS_PRICE_STEP_AVERAGE: 0.025,
    GAS_PRICE_STEP_HIGH: 0.08,
    FEATURES: ['stargate', 'ibc-transfer'],
};
